Python 3.13.7 (tags/v3.13.7:bcee1c3, Aug 14 2025, 14:15:11) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> #Richard Comins
... #9/17/2025
... #P1HW1
... #This program collects information from user, processes the information collected and displays the results. 
... 
... print("-----Calculating Exponents-----\n")
... 
... 
... 
... #Ask user to enter an integer which will be used as the base value.
... 
... num1 = int(input("Enter an integer as the base value: "))
... 
... #Ask user to enter a second number which will be used as the exponent.
... 
... num2 = int(input("Enter an integer as the exponent: "))
... 
... 
... print(num1,"raised to the power of",num2,"is",num1**num2)
... 
... 
... print("-----Additions and Subtractions----\n")
... 
... 
... #Ask user to enter an integer to be used as the starting number.
... 
... first_num = int(input("Enter an integer as the starting number:  "))
... 
... #Ask the user for another interger to be used as the second number.
... 
... second_num = int(input("Enter another integer as the second number: "))
... 
... #Ask the user for another integer to used as the third number.
...  
... third_num = int(input("Enter an integer as a third number to be used for subtraction purposes: "))

print((first_num, + second_num), - third_num)


